SELECT AIRBRANCH.LOOKUPIAIPACCOUNTS.NUMACCOUNTCODE,
  AIRBRANCH.LOOKUPIAIPACCOUNTS.STRACCOUNTDESC,
  AIRBRANCH.LOOKUPEPDBRANCHES.STRBRANCHDESC,
  AIRBRANCH.LOOKUPEPDPROGRAMS.STRPROGRAMDESC,
  AIRBRANCH.LOOKUPEPDUNITS.STRUNITDESC
FROM AIRBRANCH.LOOKUPIAIPACCOUNTS
LEFT JOIN AIRBRANCH.LOOKUPEPDBRANCHES
ON AIRBRANCH.LOOKUPEPDBRANCHES.NUMBRANCHCODE = AIRBRANCH.LOOKUPIAIPACCOUNTS.NUMBRANCHCODE
LEFT JOIN AIRBRANCH.LOOKUPEPDPROGRAMS
ON AIRBRANCH.LOOKUPEPDPROGRAMS.NUMPROGRAMCODE = AIRBRANCH.LOOKUPIAIPACCOUNTS.NUMPROGRAMCODE
LEFT JOIN AIRBRANCH.LOOKUPEPDUNITS
ON AIRBRANCH.LOOKUPEPDUNITS.NUMUNITCODE = AIRBRANCH.LOOKUPIAIPACCOUNTS.NUMUNITCODE
ORDER BY AIRBRANCH.LOOKUPIAIPACCOUNTS.NUMACCOUNTCODE