<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Coming+Soon|Lato:400,400italic,700">
<link rel="stylesheet" href="/assets/style.css">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png?v=69kRrvbXdL">
<link rel="icon" type="image/png" href="/favicon-32x32.png?v=69kRrvbXdL" sizes="32x32">
<link rel="icon" type="image/png" href="/favicon-16x16.png?v=69kRrvbXdL" sizes="16x16">
<link rel="manifest" href="/manifest.json?v=69kRrvbXdL">
<link rel="mask-icon" href="/safari-pinned-tab.svg?v=69kRrvbXdL" color="#5bbad5">
<link rel="shortcut icon" href="/favicon.ico?v=69kRrvbXdL">
<meta name="theme-color" content="#e5f6fa">
<link rel="stylesheet" href="//georgia.gov/profiles/georgiagov/modules/custom/gagov_external_blocks/css/gagov_external_blocks-topper.css" />
<link rel="stylesheet" href="//georgia.gov/profiles/georgiagov/modules/custom/gagov_external_blocks/css/gagov_external_blocks-footer.css" />
