
' This file is used by Code Analysis to maintain SuppressMessage 
' attributes that are applied to this project.
' Project-level suppressions either have no target or are given 
' a specific target and scoped to a namespace, type, member, etc.

Imports System.Diagnostics.CodeAnalysis

<Assembly: SuppressMessage("Usage", "CA1801:Review unused parameters", Justification:="Parameter used in Release, but not Debug build", Scope:="member", Target:="~M:Iaip.ErrorReporting.ErrorReport(System.Exception,System.String,System.String,System.Boolean)")>
<Assembly: SuppressMessage("Usage", "CA1801:Review unused parameters", Justification:="Parameter used in Release, but not Debug build", Scope:="member", Target:="~M:Iaip.IaipExceptionManager.HandleException(System.Exception,System.String)")>
<Assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification:="This multidimensional array is integral to the design of the IAIP.", Scope:="member", Target:="~F:Iaip.Constants.AccountFormAccess")>
<Assembly: SuppressMessage("Security", "CA3075:Insecure DTD processing in XML", Justification:="Code auto-generated by Crystal Reports tool.", Scope:="member", Target:="~M:Iaip.CrDataSet.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")>
<Assembly: SuppressMessage("Security", "CA3075:Insecure DTD processing in XML", Justification:="Code auto-generated by Crystal Reports tool.", Scope:="member", Target:="~M:Iaip.CrDataSet.GetSchemaSerializable~System.Xml.Schema.XmlSchema")>
<Assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification:="Unneeded")>
<Assembly: SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification:="Suppressing all globalization warnings")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="Suppressing all globalization warnings")>
<Assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification:="Suppressing all globalization warnings")>
